/*
* generated by Xtext
*/
package com.dawsonsystems.outline;

import org.eclipse.xtext.ui.common.editor.outline.transformer.AbstractDeclarativeSemanticModelTransformer;

/**
 * customization of the default outline structure
 * 
 */
public class SwiftTransformer extends AbstractDeclarativeSemanticModelTransformer {
	
}
