/*
* generated by Xtext
*/
package com.dawsonsystems.parser.antlr;

import org.antlr.runtime.ANTLRInputStream;
import org.eclipse.xtext.parser.antlr.ITokenDefProvider;
import org.eclipse.xtext.parser.IParseResult;
import org.eclipse.xtext.parser.ParseException;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

import com.google.inject.Inject;

import com.dawsonsystems.services.SwiftGrammarAccess;

public class SwiftParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject 
    protected ITokenDefProvider antlrTokenDefProvider;
	
	@Inject
	private SwiftGrammarAccess grammarAccess;
	
	@Override
	protected IParseResult parse(String ruleName, ANTLRInputStream in) {
		com.dawsonsystems.parser.antlr.internal.InternalSwiftLexer lexer = new com.dawsonsystems.parser.antlr.internal.InternalSwiftLexer(in);
		XtextTokenStream stream = new XtextTokenStream(lexer, antlrTokenDefProvider);
		stream.setInitialHiddenTokens();
		com.dawsonsystems.parser.antlr.internal.InternalSwiftParser parser = new com.dawsonsystems.parser.antlr.internal.InternalSwiftParser(
				stream, getElementFactory(), grammarAccess);
		parser.setTokenTypeMap(antlrTokenDefProvider.getTokenDefMap());
		try {
			if(ruleName != null)
				return parser.parse(ruleName);
			return parser.parse();
		} catch (Exception re) {
			throw new ParseException(re.getMessage(),re);
		}
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Message";
	}
	
	public SwiftGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(SwiftGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
