/*
 * generated by Xtext
 */
package com.dawsonsystems;

/**
 * Use this class to register components to be used within the IDE.
 */
public class SwiftRuntimeModule extends com.dawsonsystems.AbstractSwiftRuntimeModule {

	
}
