/*
* generated by Xtext
*/
package com.dawsonsystems.contentassist;

import com.dawsonsystems.contentassist.AbstractSwiftProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class SwiftProposalProvider extends AbstractSwiftProposalProvider {

}
